"""
Certificate download endpoints
Serve PDF certificates generated by certificate-service
"""
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse
from pathlib import Path
from ..auth import get_current_user, require_admin
from ..database import get_pool
import asyncpg

router = APIRouter()

# Certificate storage path (mounted from certificate-service volume)
CERT_STORAGE = Path("/app/certificates")


@router.post("/init-certificates")
async def init_certificates(current_user: dict = Depends(require_admin)):
    """
    Trigger certificate generation for all approved submissions without certificates
    Admin only - This endpoint notifies the certificate-service to check for new submissions
    
    Note: Actual PDF generation is handled by the certificate-service
    """
    pool = await get_pool()
    
    async with pool.acquire() as conn:
        # Count submissions needing certificates
        count = await conn.fetchval("""
            SELECT COUNT(*)
            FROM ho_so_xu_ly
            WHERE ket_qua = 'approved' 
            AND (duong_dan_chung_nhan IS NULL OR duong_dan_chung_nhan = '')
        """)
        
        return {
            "success": True,
            "message": f"Found {count} submissions pending certificate generation",
            "count": count,
            "note": "Certificate-service will process these in the next polling cycle (within 30 seconds)"
        }


@router.get("/download/{filename}")
async def download_certificate(filename: str, current_user: dict = Depends(get_current_user)):
    """
    Download certificate PDF file
    Requires authentication
    """
    # Security: only allow .pdf files and prevent directory traversal
    if not filename.endswith('.pdf') or '/' in filename or '\\' in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")
    
    file_path = CERT_STORAGE / filename
    
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Certificate not found")
    
    return FileResponse(
        path=str(file_path),
        media_type="application/pdf",
        filename=filename
    )


@router.get("/{submission_id}.pdf")
async def get_certificate_by_submission(submission_id: str, current_user: dict = Depends(get_current_user)):
    """
    Get certificate for a specific submission
    Returns the PDF file if exists
    """
    pool = await get_pool()
    
    async with pool.acquire() as conn:
        submission = await conn.fetchrow("""
            SELECT duong_dan_chung_nhan
            FROM ho_so_xu_ly
            WHERE id = $1
        """, submission_id)
        
        if not submission:
            raise HTTPException(status_code=404, detail="Submission not found")
        
        if not submission['duong_dan_chung_nhan']:
            raise HTTPException(status_code=404, detail="Certificate not generated yet")
        
        # Extract filename from path (e.g., "/certificates/cert_xxx.pdf" -> "cert_xxx.pdf")
        cert_path = submission['duong_dan_chung_nhan']
        filename = Path(cert_path).name
        
        file_path = CERT_STORAGE / filename
        
        if not file_path.exists():
            raise HTTPException(status_code=404, detail="Certificate file not found")
        
        return FileResponse(
            path=str(file_path),
            media_type="application/pdf",
            filename=filename
        )
